/* Primitive Data Types
Primitive data types in JavaScript include:

Numbers - Integers, floats
Strings - Any data under single quote, double quote or backtick quote
Booleans - true or false value
Null - empty value or no value
Undefined - a declared variable without a value let num 
Symbol - A unique value that can be generated by Symbol constructor

Non-primitive data types in JavaScript includes:
Objects
Arrays
Now, let us see what exactly primitive and non-primitive data types mean. 
Primitive data types are immutable(non-modifiable) data types. 
Once a primitive data type is created we cannot modify it.

Example:   */
//when we declare a variable we use the key word let, const or var
//let is used when a variable will change
//
let word //undefined or uninitialized variable ---the only thing we did here was declare a variable
 let word = 'Javascript' //initialized variable or defined variable
 console.log(word)

//If we try to modify the string stored in variable word, JavaScript 
//should raise an error. Any data type under a single quote, 
//double quote, or backtick quote is a string data type

word[0] = 'Y'
console.log(word)

//This expression does not change the string stored in the variable word. 
//So, we can say that strings are not modifiable or in other words immutable. 
//Primitive data types are compared by its values. 
//Let us compare different data values. See the example below:

 let numOne = 3
 let numTwo = 3
 console.log(numOne == numTwo)      // true

 let js = 'JavaScript'
 let py = 'Python'
 console.log(js == py)             //false 


//boolean value
 let lightOn = true
 let lightOff = false

 console.log(lightOn == lightOff) // false

